name = "hianime-api"
main = "src/worker.js"
compatibility_date = "2026-02-12"
compatibility_flags = ["nodejs_compat"]

[vars]
ORIGIN = "ani.devxjin.site,anime.devxjin.site,devzanime.vercel.app"
RATE_LIMIT_WINDOW_MS = "60000"
RATE_LIMIT_LIMIT = "100"
ERROR_COLLECTOR_ENABLED = "1"
ERROR_COLLECTOR_MAX_ENTRIES = "250"
ERROR_COLLECTOR_INCLUDE_STACK = "0"
